#!/bin/sh

set -e

testdir=$(dirname $(readlink -f "$0"))
envdir="$testdir/.venv"

setup()
{
    if [ -d $envdir ]; then
	. $envdir/bin/activate
    else
	python3 -m venv $envdir
	. $envdir/bin/activate
	python3 -m pip install -r $testdir/requirements.txt
    fi

    export PYTHONPATH=$testdir
}

ninepm()
{
    exec $testdir/../9pm/9pm.py "$@"
}

execute()
{
    exec "$@"
}

usage()
{
    cat <<EOF
usage: ${0} <command> [<args>]

  Commands:

    9pm <9pm-args>
      Run 9pm in a Python venv with all of Infamy's requirements
      installed.

    exec <case> <case-args>
      Directly run a single test-case in a Python venv with all of
      Infamy's requirements installed.

    init
      (Re)install all of Infamy's requirements in a new Python venv.

    help
      Display this message.

EOF
}

if [ $# -lt 1 ]; then
    usage && exit 1
fi

cmd=${1}
shift

case ${cmd} in
    "9pm")
	setup
	ninepm "$@"
	;;
    "init")
	rm -rf "$testdir/.venv"
	setup
	;;
    "exec")
	setup
	execute "$@"
	;;
    "help")
	usage && exit 0
	;;
    *)
	usage && exit 1
esac
